# Generated by Django 3.2.7 on 2021-09-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_alter_additem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='quantity',
            field=models.CharField(max_length=1000),
        ),
    ]
