# Generated by Django 3.2.7 on 2021-09-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_alter_additem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('BOUGHT', 'BOUGHT'), ('NOT AVAILABLE', 'NOT AVAILABLE')], default='PENDING', max_length=200),
        ),
    ]
